### ISSUE TITLE
Code of 'awakening_latent_grounding'

### ISSUE THREAD

**Issue by 1160300911** [microsoft/ContextualSP#11]
Hi,

Could you please share the source code of 'awakening_latent_grounding'? This work has inspired me a lot.

Thanks.

**Comment by SivilTaram** [comment]
@1160300911 Sure! I'm still cleaning the code (sorry for the so late prepartion) since I'm busy with job interviewing few months ago. I will mention you here when it is uploaded, and it will be ideally released in two weeks.

**Comment by 1160300911** [comment]
Hi,

Thanks for your reply! I would appreciate it if you could do so.

Best wishes.

**Comment by SivilTaram** [comment]
Sorry for the really late response. It costs me several months to merge the codebase from different collaborators on different datasets - so it's so late to release. Feel free to ask any question if you have on the codebase.
