### ISSUE TITLE
using incomplete_utterance_rewriting in English dataset is very weak

### ISSUE THREAD

**Issue by Takeru0618** [microsoft/ContextualSP#12]
how to use Bert in training?

**Comment by SivilTaram** [comment]
@Takeru0618 Hi, thanks for your interest in our work. However, I do not know what you want to say exactly. Do you need a config file with BERT for fine-tuning on Englished based task (You can refer to those Chinese configs with BERT and modify them to adapt to BERT easily). Or you want to discuss about why RUN is weak on your English dataset.

**Comment by Takeru0618** [comment]
@SivilTaram  Thanks, both of your two answers are what I want to ask, 
I will try  BERT for fine-tuning on Englished based task,
but, I really get  weak results in my dataset without BERT, will it be work ? ......

**Comment by SivilTaram** [comment]
@Takeru0618 What kind of tasks would you like to try? Can you give some examples? What configuration do you use for Enligsh-based tasks? I'd like to help you more if you could give more details.

**Comment by Takeru0618** [comment]
@SivilTaram 
Thank you very much!!

I would like to use this model in a daily dialogue dataset.
for example:

hannah: hey, do you have betty's number?
amanda: lemme check
hannah: <file_gif>
amanda: sorry, can't find it.
amanda: ask larry
amanda: he called her last time we were at the park together
hannah: i don't know him well
hannah: <file_gif>
amanda: don't be shy, he's very nice
hannah: if you say so..
hannah: i'd rather you texted him
amanda: just text him 🙂
hannah: urgh.. alright
hannah: bye
amanda: bye bye

The result is:

hannah: hey , do you have betty 's number ?
amanda: lemme check ?
hannah: <file_gif> hey
amanda: sorry , ca n't find hannah: hey 's .
amanda: ask larry ?
amanda: he called her last time we were at the park together
hannah: i do n't know hannah: hey well
hannah: <file_gif>
amanda: do n't be shy , hannah: 's very nice
hannah: if you say so ..
hannah: i 'd rather you texted hannah: hey
amanda: just text hannah: hey 🙂
hannah: urgh .. alright
hannah: bye
amanda: bye bye

and my configuration is

{
	"random_seed": 42,
	"numpy_seed": 42,
	"pytorch_seed": 42,
	"dataset_reader": {
		"type": "rewrite",
		"lazy": false,
		"super_mode": "before",
		"joint_encoding": true,
		"extra_stop_words": [
			"'s",
			"besides",
			"the",
			"in",
			"of"
		]
	},
	"model": {
		"type": "rewrite",
		"word_embedder": {
			"tokens": {
				"type": "embedding",
				"embedding_dim": 100,
				"trainable": true,
				"padding_index": 0
			}
		},
		"text_encoder": {
			"type": "lstm",
			"input_size": 100,
			"hidden_size": 200,
			"bidirectional": true,
			"num_layers": 1
		},
		"inp_drop_rate": 0.2,
		"out_drop_rate": 0.2,
		"feature_sel": 115,
		"loss_weights": [
			0.1,
			0.4,
			0.5
		],
		"super_mode": "before",
		"unet_down_channel": 128,
		"enable_training_log": false
	},
	"iterator": {
		"type": "basic",
		"batch_size": 4
	},
	"validation_iterator": {
		"type": "basic",
		"batch_size": 4
	},
	"trainer": {
		"num_epochs": 100,
		"cuda_device": 0,
		"patience": 10,
		"validation_metric": "+BLEU4",
		"optimizer": {
			"type": "adam",
			"lr": 2e-4
		},
		"learning_rate_scheduler": {
			"type": "reduce_on_plateau",
			"factor": 0.5,
			"mode": "max",
			"patience": 5
		},
		"num_serialized_models_to_keep": 10,
		"should_log_learning_rate": true
	}
}


I just used this configure as the one after joining Bert
{
	"random_seed": 42,
	"numpy_seed": 42,
	"pytorch_seed": 42,
	"dataset_reader": {
		"type": "rewrite",
		"lazy": false,
		"super_mode": "before",
		"joint_encoding": true,
        "use_bert": true,
        "language": "en",
		"extra_stop_words": [
			"'s",
			"besides",
			"the",
			"in",
			"of"
		]
	},
	"model": {
		"type": "rewrite",
		"word_embedder": {
			"bert": {
				"type": "bert-pretrained",
				"pretrained_model": "bert-base-uncased",
				"top_layer_only": true,
				"requires_grad": true
			},
			"allow_unmatched_keys": true,
			"embedder_to_indexer_map": {
				"bert": [
					"bert",
					"bert-offsets",
					"bert-type-ids"
				]
			}
		},
		"text_encoder": {
			"type": "lstm",
			"input_size": 100,
			"hidden_size": 200,
			"bidirectional": true,
			"num_layers": 1
		},
		"inp_drop_rate": 0.2,
		"out_drop_rate": 0.2,
		"feature_sel": 115,
		"loss_weights": [
			0.1,
			0.4,
			0.5
		],
		"super_mode": "before",
		"unet_down_channel": 128,
		"enable_training_log": false
	},
	"iterator": {
		"type": "basic",
		"batch_size": 4
	},
	"validation_iterator": {
		"type": "basic",
		"batch_size": 4
	},
	"trainer": {
		"num_epochs": 100,
		"cuda_device": 0,
		"patience": 10,
		"validation_metric": "+BLEU4",
		"optimizer": {
			"type": "adam",
			"lr": 2e-4
		},
		"learning_rate_scheduler": {
			"type": "reduce_on_plateau",
			"factor": 0.5,
			"mode": "max",
			"patience": 5
		},
		"num_serialized_models_to_keep": 10,
		"should_log_learning_rate": true
	}
}
But the program reported an error

Traceback (most recent call last):
  File "/home/ubuntu/users/wangsiyi/miniconda3/envs/torch_2/bin/allennlp", line 8, in <module>
    sys.exit(run())
  File "/home/ubuntu/users/wangsiyi/miniconda3/envs/torch_2/lib/python3.7/site-packages/allennlp/run.py", line 18, in run
    main(prog="allennlp")
  File "/home/ubuntu/users/wangsiyi/miniconda3/envs/torch_2/lib/python3.7/site-packages/allennlp/commands/__init__.py", line 102, in main
    args.func(args)
  File "/home/ubuntu/users/wangsiyi/miniconda3/envs/torch_2/lib/python3.7/site-packages/allennlp/commands/train.py", line 124, in train_model_from_args
    args.cache_prefix)
  File "/home/ubuntu/users/wangsiyi/miniconda3/envs/torch_2/lib/python3.7/site-packages/allennlp/commands/train.py", line 168, in train_model_from_file
    cache_directory, cache_prefix)
  File "/home/ubuntu/users/wangsiyi/miniconda3/envs/torch_2/lib/python3.7/site-packages/allennlp/commands/train.py", line 226, in train_model
    cache_prefix)
  File "/home/ubuntu/users/wangsiyi/miniconda3/envs/torch_2/lib/python3.7/site-packages/allennlp/training/trainer_pieces.py", line 42, in from_params
    all_datasets = training_util.datasets_from_params(params, cache_directory, cache_prefix)
  File "/home/ubuntu/users/wangsiyi/miniconda3/envs/torch_2/lib/python3.7/site-packages/allennlp/training/util.py", line 178, in datasets_from_params
    train_data = dataset_reader.read(train_data_path)
  File "/home/ubuntu/users/wangsiyi/miniconda3/envs/torch_2/lib/python3.7/site-packages/allennlp/data/dataset_readers/dataset_reader.py", line 130, in read
    instances = self._read(file_path)
  File "./data_reader.py", line 92, in _read
    'rb')) if ins]
EOFError: Ran out of input

**Comment by SivilTaram** [comment]
@Takeru0618 Thanks for the response, I would like to be more happy if you could adjust the format instead of plain text.

First, I think the task can be tackled by our code, although I do not understand why it performs bad in your task.

Second, I think the non-BERT verion should work well, if you fine-tune the hyper-parameter `loss_weights`. The current weight `[0.1, 0.4, 0.5]` is for the dataset CANARD, you should fine-tune it to be suitable for your dataset & task.

Overall, the bert-based configuration seems well for me. There is only a little error since the `input_size` for the `text_encoder` is aligned with the output dimension of BERT. Please refer to other configs to correct that.

Last, as for the `EOFError`, it seems that your dataset is not ready to read. Does the dataset follow the same format with other datasets used in this repo?

**Comment by Takeru0618** [comment]
@SivilTaram 

Thank you very much!!!

I have one more question, please forgive my ignorance

If I use Bert in configs like this
<img width="475" alt="image" src="https://user-images.githubusercontent.com/82857532/144629043-bb6f456f-d701-4a87-a3df-1460a3806466.png">

do I need to add glove in .sh
![31341638545188_ pic](https://user-images.githubusercontent.com/82857532/144629123-91be35ad-67be-496e-b300-ff17b748baee.jpg)
?

**Comment by SivilTaram** [comment]
@Takeru0618 You do not need to pass by glove file path since you do not use it in the following command. It stops because the early-stop, you could increase the "patience" to a larger number.

**Comment by Takeru0618** [comment]
Thank you for your answers, I would also like to ask. If I terminate the training prematurely, the model.tar.gz file is not automatically generated. How to manually generate this file

**Comment by SivilTaram** [comment]
@Takeru0618 You may turn to `allennlp` document (https://github.com/allenai/allennlp) to solve the problem. It is out of the scope of this repo.
