### ISSUE TITLE
multi replcae position in same current position

### ISSUE THREAD

**Issue by lianzhaoy** [microsoft/ContextualSP#15]
Hi, 

You pointed out that there are multiple inserts in the same location in your article, but what if context_seq has more than one replace on the current_seq [m,n] position?

Thanks!

**Comment by SivilTaram** [comment]
@lianzhaoy Thanks for your interest on our work! Sorry I cannot get the point, could you please illustrate it with an example? Thanks!

**Comment by lianzhaoy** [comment]
Given a word-level Edit matrix, there is a case where [x3,x4] is substituted with [c3,c5] and [c6,c8].
How to deal with above situation

**Comment by SivilTaram** [comment]
@lianzhaoy That's a good question. If I remember it correctly, we will follow the original order to concatenate [c3,c5] and [c6,c8] to jointly subsitute [x3,x4]. The final sequence should be [x1,x2,c3 ... c5,c6 ... c8]. That will be useful for scenarios where one pronoun (e.g., they) referrs multiple entities (e.g., Jack and William).

**Comment by SivilTaram** [comment]
Closed since there is no more activity. Feel free to re-open.
