### ISSUE TITLE
about Incomplete Utterance Rewriting as Semantic Segmentation label problem

### ISSUE THREAD

**Issue by LLLLLLoki** [microsoft/ContextualSP#2]
Do you release your own labeled data sets? (There are three labels.)

**Comment by SivilTaram** [comment]
@LLLLLLoki It may not be released because of the potential copyright/license problem, but we will undoubtedly release the processing code (now we're preparing the code, it will be released before Oct. 25).

**Comment by LLLLLLoki** [comment]
Thanks for your contribution and Look forward to your code:)

**Comment by SivilTaram** [comment]
@LLLLLLoki Hi, we have released the main boy of our code (remaining scripts & pre-trained model weights are being uploaded). Hope you enjoy it ☕
