### ISSUE TITLE
Could you share the post-processing script or the post-processed train data for UniSar?

### ISSUE THREAD

**Issue by cabisarri** [microsoft/ContextualSP#32]

**Comment by SivilTaram** [comment]
Hi @DreamerDeo, could you help on this?

**Comment by DreamerDeo** [comment]
Hi @cabisarri, thanks for your interest in our work.

The train data follows the same format as the dev data.
Given that preprocessing would take a lot of time and users tend to directly adopt the unisar for infence, the current code only preprocess the dev-set. However, you could simple **_comment_** out or **_modify_** the following lines to support train-set then retrain the model by yourself.

https://github.com/microsoft/ContextualSP/blob/ad7d7979957207e5fe23db7db1cad1066665b66b/unified_parser_text_to_sql/step1_schema_linking.py#L432
https://github.com/microsoft/ContextualSP/blob/ad7d7979957207e5fe23db7db1cad1066665b66b/unified_parser_text_to_sql/step2_serialization.py#L167

Change `fairseq-preprocess` function here https://github.com/microsoft/ContextualSP/blob/ad7d7979957207e5fe23db7db1cad1066665b66b/unified_parser_text_to_sql/step2_serialization.py#L9 as 
>     cmd = f"python -m multiprocessing_bpe_encoder \
>               --encoder-json ./BART-large/encoder.json \
>               --vocab-bpe ./BART-large/vocab.bpe \
>               --inputs {generate_path}/train.src \
>               --outputs {generate_path}/train.bpe.src \
>               --workers 1 \
>               --keep-empty"
>     run_command(cmd)
> 
>     cmd = f"python -m multiprocessing_bpe_encoder \
>             --encoder-json ./BART-large/encoder.json \
>             --vocab-bpe ./BART-large/vocab.bpe \
>             --inputs {generate_path}/train.tgt \
>             --outputs {generate_path}/train.bpe.tgt \
>             --workers 1 \
>             --keep-empty"
>     run_command(cmd)
> 
>     cmd = f"python -m multiprocessing_bpe_encoder \
>             --encoder-json ./BART-large/encoder.json \
>             --vocab-bpe ./BART-large/vocab.bpe \
>             --inputs {generate_path}/dev.src \
>             --outputs {generate_path}/dev.bpe.src \
>             --workers 1 \
>             --keep-empty"
>     run_command(cmd)
> 
>     cmd = f"python -m multiprocessing_bpe_encoder \
>             --encoder-json ./BART-large/encoder.json \
>             --vocab-bpe ./BART-large/vocab.bpe \
>             --inputs {generate_path}/dev.tgt \
>             --outputs {generate_path}/dev.bpe.tgt \
>             --workers 1 \
>             --keep-empty"
>     run_command(cmd)
> 
>     cmd = f'fairseq-preprocess --source-lang "src" --target-lang "tgt" \
>         --trainpref {generate_path}/train.bpe \
>         --validpref {generate_path}/dev.bpe \
>         --destdir {generate_path}/bin \
>         --workers 2 \
>         --srcdict ./BART-large/dict.src.txt \
>         --tgtdict ./BART-large/dict.tgt.txt '
> 
>     subprocess.Popen(
>         cmd, universal_newlines=True, shell=True,
>         stdout=subprocess.PIPE, stderr=subprocess.PIPE).communicate()

**Comment by cabisarri** [comment]
Thanks a lot for the details. I will give it a try.

**Comment by SivilTaram** [comment]
Closed since there is no more activity.
