### ISSUE TITLE
LogiGAN: dataset creation

### ISSUE THREAD

**Issue by Golovneva** [microsoft/ContextualSP#36]
Hi! Thank you for sharing the code for LogiGAN paper.
I'm having troubles creating training set. In particular:
1. [Here](https://github.com/microsoft/ContextualSP/blob/master/logigan/corpus_construction/mlm_corpus/construct_conclusion.sh#L8) code refers to non-exiting script. I have replaced commands with "python corpus_construction.py --start 0 --end 500 --indicator_type conclusion &" - is it the right way to do?
2. elastic_search/build_gen_train/ver_train [refers to files](https://github.com/microsoft/ContextualSP/blob/master/logigan/corpus_construction/elastic_search/build_gen_train.py#L118) that do not exist in the bookcorpus, and there are no instructions how to create them. Is there a script/link to generate gan_corpus_new/beta/gen_train_B.jsonl and gan_corpus_new/beta/ver_train.jsonl files?

**Comment by SivilTaram** [comment]
Hi Wanjun, can you help answer the question? @zhongwanjun

**Comment by zhongwanjun** [comment]
Hi. Thanks. I will upload the created data files, and model checkpoints ASAP. Please stay tuned.

**Comment by zhongwanjun** [comment]
Hi, I have already uploaded the data and code in the released data in this repo.

**Comment by SivilTaram** [comment]
@Golovneva You can find it [here](https://github.com/microsoft/ContextualSP/releases/tag/logigan).

**Comment by Golovneva** [comment]
Thanks a lot!
