### ISSUE TITLE
Whether the model of 'awakening_latent_grounding' is open source.

### ISSUE THREAD

**Issue by Soul-Immortal** [microsoft/ContextualSP#38]
Hi! Your paper has inspired me a lot, and I am very grateful.

I wonder if the code for this paper will be open source. Because it hasn't been updated on github.

**Comment by SivilTaram** [comment]
@Soul-Immortal I'm so sorry for the inconvenience. I haven't been able to clean up the code because of a lot of things have been taking away my efforts. But I think I should at least upload a version, and hope that helps.

**Comment by SivilTaram** [comment]
@Soul-Immortal Have uploaded the not-totally-ready version of our code. I will try my best to clean up all the code and finish the detailed instruction on how to run it from scratch in next week. Note that the current version does not include the spider preprocessing script, and I will also try to find it out. Thanks for your understanding

**Comment by Soul-Immortal** [comment]
> @Soul-Immortal Have uploaded the not-totally-ready version of our code. I will try my best to clean up all the code and finish the detailed instruction on how to run it from scratch in the following weeks (hopefully 1~2 week). Note that the current version does not include the spider preprocessing script, and I will also try to find it out. Thanks for your understanding

Thank you for your reply. Meanwhile, thank you for uploading the code, which gives me a good opportunity to learn.
Looking forward to the totally-ready version of the code.

**Comment by SivilTaram** [comment]
@Soul-Immortal Sorry for the late response! I have finalized the cleaning on the grounding part and can successfully reproduce the results in the paper following the current code structure. Please feel free to try! 

A little explanation on the difference between the previous version and the current version: in fact the current version is the optimized experimental code, and the previous code is further optimized for better organization. But in fact the previous version is hard to read, and so I decide to clean on the experimental code.

We will release the trained grounding model weights, and also the commands to train the baseline parser with our grounding model. Please stay tuned ☕ Really sorry for the delayed open-source.

**Comment by SivilTaram** [comment]
Please feel free to re-open if you have further questions!
