### ISSUE TITLE
The requirements are not described in LEMON

### ISSUE THREAD

**Issue by olivehair** [microsoft/ContextualSP#46]
I would like to reproduce the results again in the LEMON paper. Since I have to pre-train and fine-tune a model using BART, I don't know what version of Python, fairseq, etc. was used in their work!

Can anyone help?

**Comment by SivilTaram** [comment]
@olivehair Thanks for your interest in our work! We do not specify a specific version of fairseq here. So I would recommend you to install the latest fairseq using python 3.8. If it does not work, please report here and I will try to help. Thanks!
