### ISSUE TITLE
Human Simulator Missing

### ISSUE THREAD

**Issue by karthik446** [microsoft/ContextualSP#5]
The src.components.human_simulator file is missing.

**Comment by SivilTaram** [comment]
@karthik446 Thank you for your attention on our work, I will tell the author to respond here asap.

**Comment by SivilTaram** [comment]
@karthik446 The first author is preparing a clean version of the human simulator script since there are redundant code snippets, and please stay tuned. We will try our best to update it in one week.

**Comment by karthik446** [comment]
@SivilTaram Thank you so much :)

**Comment by hotessy** [comment]
Hi @SivilTaram,
Has the `HumanSimulator` script been updated? If yes, please help me find it in the [interactive text to SQL repository](https://github.com/microsoft/ContextualSP/tree/master/interactive_text_to_sql)?

There are other `import` errors in this version as well.

**Comment by SivilTaram** [comment]
Sorry the first author cannot recover the `HumanSimulator` class since the original codebase is cleared after his internship 😓 You may have to implement one by yourself. So sorry for the inconvenience.
