### ISSUE TITLE
awakening_latent_grounding dataset missing.

### ISSUE THREAD

**Issue by Soul-Immortal** [microsoft/ContextualSP#50]
Hello, it seems that part of the WTQ dataset is missing due to the problem of github. Could you please upload the missing part to github again. Thanks!

**Comment by SivilTaram** [comment]
@Soul-Immortal Hello, sorry I do not get exact the problem. Do you mean the preprocessed dataset of WTQ?

**Comment by Soul-Immortal** [comment]
> @Soul-Immortal Hello, sorry I do not get exactly the problem. Do you mean the preprocessed dataset of WTQ?

The path is ”/awakening_latent_grounding/data/wtq_grounding/json/“. 
When I want to download it, just 1000 files can be downloaded. And tell me a limitation," Sorry, we had to truncate this directory to 1,000 files. 1,108 entries were omitted from the list.". 
Is there any way to see the omitted files or how to download all files?

**Comment by SivilTaram** [comment]
@Soul-Immortal Thanks for the feedback, and I just realized the problem 😓 Will upload a zipped files later.

**Comment by SivilTaram** [comment]
@Soul-Immortal Fix the problem. Feel free to re-open the issue if there is any problem. Sorry for the confusion!
