### ISSUE TITLE
Unable to re-produce LANE results on SCAN length split

### ISSUE THREAD

**Issue by ag1988** [microsoft/ContextualSP#8]
Hello,

I am running the training command as instructed in LANE:
```CUDA_VISIBLE_DEVICES=0 python main.py --mode train --checkpoint length_model --task length```
but am not able to get the expected results. I tried this with random seeds 1, 2. 
I am attaching the log files - can you please let me know what I might be doing wrong. 
[length_model_seed2.log](https://github.com/microsoft/ContextualSP/files/6199464/length_model_seed2.log)
[length_model.log](https://github.com/microsoft/ContextualSP/files/6199465/length_model.log)

**Comment by SivilTaram** [comment]
@ag1988 Thanks for your interest on our work! I will look into this problem and get back here in 2 days. Please stay tuned!

**Comment by SivilTaram** [comment]
@ag1988 Hi, sorry for the mistake on curriculum setting. I have updated the code, and you're expected to reproduce the results of `length` stably. Please try again, Thanks ☕

**Comment by ag1988** [comment]
Thanks for the prompt response Qian! I'll run the updated code and get back
to you if the issue persists.

Regards,
Ankit
